### ISSUE TITLE
FormTesterMixin is inherited incorrectly

### ISSUE THREAD

**Issue by kurtgn** [realpython/book3-exercises#9]
Hi,

first of all - thanks for the awesome book, all three parts! It's been my everyday book for several months now.

Now - an issue:

If I inherit a mixin like this
```
class FormTests(TestCase, FormTesterMixin):
```

the `assertFormError()` function which exists in the base Django `TransactionTestCase` will not be overridden and thus will throw an error when validating forms:

```
File "/Users/1111/.virtualenvs/d3/lib/python2.7/site-packages/django/test/testcases.py", line 711, in assertFormError
    contexts = to_list(response.context)
AttributeError: type object 'SigninForm' has no attribute 'context'
```

so you should first inherit from the mixin, and than from the base class:
```
class FormTests(FormTesterMixin, TestCase):
```

or maybe this is just my Python giving me a hard time.

**Comment by kurtgn** [comment]
p.s. These typos and the work they generate make the book even more valuable :)

**Comment by j1z0** [comment]
@kurtgin can you confirm what version of django your using

**Comment by kurtgn** [comment]
the one from requirements.txt from https://github.com/realpython/book3-exercises/blob/master/_chapters/_start_here.zip?raw=true , 1.5.5

**Comment by kurtgn** [comment]
and Python 2.7.5

**Comment by kurtgn** [comment]
That's en error on my part. I used django.test.TestCase class, and you are using unittest.TestCase. If I implement the test exactly according to the book, everything works properly.

**Comment by j1z0** [comment]
Well like you said. It's really good for learning. :). I'll go back and look at the chapter and see if we can make it more clear though. 

Also thanks for taking the time to feedback. I really appreciate that.
